spring:
  application:
    name: xmall-inventory
  datasource:
    url: jdbc:mysql://mysql.orkva.com:3307/xmall_inventory?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 7#f82CF3K8jwAq&Zp*L2489tPK*9E@78
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080
