### list sku inventory
GET http://localhost:8080/inventories/sku
Accept: application/json

### list abailable batches inventories by sku
GET http://localhost:8080/inventories/batches/available?skuId=1
Accept: application/json

### list batches chages
GET http://localhost:8080/inventories/batches/changes
Content-Type: application/json
Accept: application/json

{
  "skuId": 4
}

### list all batches inventories
GET http://localhost:8080/inventories/batches

### purchase
POST http://localhost:8080/inventories/purchase
Content-Type: application/json
Accept: application/json

{
  "skuId": 4,
  "change": 100
}

### locked
POST http://localhost:8080/inventories/locked
Content-Type: application/json
Accept: application/json

{
  "lotNumber": 1139233466680868864,
  "change": 80
}

### pickup
POST http://localhost:8080/inventories/pickup
Content-Type: application/json
Accept: application/json

{
  "lotNumber": 1139233466680868864,
  "change": 60
}

### recede
POST http://localhost:8080/inventories/recede
Content-Type: application/json
Accept: application/json

{
  "lotNumber": 1139233466680868864,
  "change": 30
}